version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups
    environment:
      - DB_USER=pyconnigeria
      - DB_PASS=postgres
      - DB_NAME=queryp
    ports:
      - "5448:5432"

