"""empty message

Revision ID: 2006d5765653
Revises: d178731b1b5f
Create Date: 2017-07-26 20:12:28.848414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2006d5765653'
down_revision = 'd178731b1b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('todo_list', sa.Column('user_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'todo_list', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
    op.add_column(u'todo_list', sa.Column('user_id', sa.Integer(), sa.ForeignKey('user.id'), nullable=True))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='foreignkey')
    op.drop_column('todo_list', 'user_id')
    # ### end Alembic commands ###
